variables:
  BUILD_ENV: "pd-build-ui-backend-373"
  RUNNING_ENV: "pd-ci-ui-backend-373"
  PYTHON_PATH: "/D/Projects/PD/softwares/python/python-3.7.3"
  BASE_PYTHON_PATH: "D:/Projects/PD/softwares/python/python-3.7.3"
  VE_PATH: "${CI_BUILDS_DIR}/${RUNNING_ENV}/Scripts/activate.ps1"
  NSSM_PATH: "/D/Projects/PD/softwares/nssm/nssm-2.24/win64/nssm.exe"
  SERVICE_NAME: "pd-ci-ui-backend"
  PACKAGE: "pd-ui-backend"
  CI_DEBUG_TRACE: "false"


stages:
  - static_analysis
  - test
  - sonar-scan
  - build-dev
  - deploy-dev
  - build-test
  - deploy-test
  - build-svt
  - deploy-svt
  - build-uat
  - deploy-uat
  - build-uat1
  - deploy-uat1
  - build-prod
  - deploy-prod
  - rollback



default:
  before_script:
    - sh app/ci_scripts/create_venv.sh
    - . $VE_PATH


flake8:
  tags:
    - pd-dev-windows-ml01q
  stage: static_analysis
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_PYPI_URL: $REGISTRY_PYPI_URL
    REGISTRY_SERVER: $REGISTRY_SERVER
  script:
    - flake8 --exit-zero --max-line-length=120
  allow_failure: true
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - merge_requests
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "dev"
  
unit-tests:
  tags:
      - pd-dev-windows-ml01q
  stage: test
  before_script:
    - . $VE_PATH
  script:
    - python -m pytest --cov=./ --cov-report xml -v --junitxml="test_results.xml"
  artifacts:
    paths:
      - coverage.xml
    reports:
      junit: test_results.xml
  allow_failure: true
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - merge_requests
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "dev"
      
Perform Sonarqube Analysis and quality gate:  # for all environments
  image: sonarsource/sonar-scanner-cli
  stage: sonar-scan
  before_script:
    - echo "Setting up for Sonarqube Analysis on PD $CI_COMMIT_REF_NAME branch"
    - apk upgrade --update-cache --available && apk add openssl
    - openssl s_client -connect   sonarqube.quintiles.com:443 | keytool -import -noprompt -alias sonarqbue_test -keystore $JAVA_HOME/lib/security/cacerts -storepass changeit
  script:
    - echo "Running Sonarqube Analysis on $CI_COMMIT_REF_NAME branch"
    - apk upgrade --update-cache --available && apk add openssl
    - sh scripts/sonarqube.sh branch > /tmp/sonar.log
    - cat /tmp/sonar.log
    - echo "Running Sonarqube quality gate on $CI_COMMIT_REF_NAME branch"
    - sh scripts/qualitygate.sh
  allow_failure: true    
  tags:
    - ca2ugitla006p-D4
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - merge_requests
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "dev"

build:
  tags:
    - pd-dev-windows-ml01q
  stage: build-dev
  variables:
    REGISTRY_PYPI_URL: $REGISTRY_PYPI_URL
    REGISTRY_PYPI_USER: $REGISTRY_PYPI_USER
    REGISTRY_PYPI_PWD: $REGISTRY_PYPI_PWD
    PACKAGE_VERSION: $CURRENT_VERSION
  before_script:
    - . $VE_PATH 
  script:
    - python setup.py sdist
    - twine upload --repository-url $REGISTRY_PYPI_URL --username ${REGISTRY_PYPI_USER} --password ${REGISTRY_PYPI_PWD}  -r nexus dist/*
  artifacts:
    paths:
      - dist/
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - merge_requests
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "dev"
  
deploy-dev1:
  tags:
    - pd-dev-windows-ml01q
  stage: deploy-dev
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_PYPI_URL: $REGISTRY_PYPI_URL
    REGISTRY_SERVER: $REGISTRY_SERVER
    PACKAGE_VERSION: $CURRENT_VERSION
    VERIFICATION_URL: "http://ca2spdml01q:8000/api/health/"
  before_script:
    - . $VE_PATH
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: dev
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - merge_requests
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "dev"
  when: manual

deploy-dev2:
  tags:
    - pd-ui-backend-dev-windows-06d-runner
  stage: deploy-dev
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_PYPI_URL: $REGISTRY_PYPI_URL
    REGISTRY_SERVER: $REGISTRY_SERVER
    PACKAGE_VERSION: $CURRENT_VERSION
    VERIFICATION_URL: "http://ca2spdml06d:8000/api/health/"
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: dev2
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - merge_requests
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "dev"
  when: manual

DEV-Rollback1:
 stage: rollback
 tags:
   - pd-dev-windows-ml01q
 variables:
   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
   REGISTRY_PYPI_URL: $REGISTRY_PYPI_URL
   REGISTRY_SERVER: $REGISTRY_SERVER
   PACKAGE_VERSION: $DEV_ROLLBACK_VERSION
   VERIFICATION_URL: "http://ca2spdml01q:8000/api/health/"
 before_script:
   - . $VE_PATH
 script:
   - sh app/ci_scripts/rollback.sh package
 environment:
   name: dev
 needs:
   - deploy-dev1
 rules:
   - if: $ENVIRONMENT == "dev"
     when: on_failure

DEV-Rollback2:
 stage: rollback
 tags:
   - pd-dev-windows-06d-runner
 variables:
   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
   REGISTRY_PYPI_URL: $REGISTRY_PYPI_URL
   REGISTRY_SERVER: $REGISTRY_SERVER
   PACKAGE_VERSION: $DEV_ROLLBACK_VERSION
   VERIFICATION_URL: "http://ca2spdml06d:8000/api/health/"
 before_script:
   - . $VE_PATH
 script:
   - sh app/ci_scripts/rollback.sh package
 environment:
   name: dev2
 needs:
   - deploy-dev2
 rules:
   - if: $ENVIRONMENT == "dev"
     when: on_failure

build-test:
  tags:
    - pd-test-windows-ml110q
  stage: build-test
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_PYPI_URL: $REGISTRY_PYPI_URL
    REGISTRY_SERVER: $REGISTRY_SERVER
    REGISTRY_PYPI_USER: $REGISTRY_PYPI_USER
    REGISTRY_PYPI_PWD: $REGISTRY_PYPI_PWD
    PACKAGE_VERSION: $CURRENT_VERSION
  script:
    - python setup.py sdist
    - twine upload --repository-url $REGISTRY_PYPI_URL --username ${REGISTRY_PYPI_USER} --password ${REGISTRY_PYPI_PWD}  -r nexus dist/*
  artifacts:
    paths:
      - dist/
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - merge_requests
      - /^pd-release/*/
    variables: 
      - $ENVIRONMENT== "test"
  
deploy-test:
  tags:
    - pd-test-windows-ml110q
  stage: deploy-test
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_PYPI_URL: $REGISTRY_PYPI_URL
    REGISTRY_SERVER: $REGISTRY_SERVER
    PACKAGE_VERSION: $CURRENT_VERSION
    VERIFICATION_URL: "http://ca2spdml110q:8000/api/health/"
  before_script:
    - . $VE_PATH
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: test
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "test"

TEST-Rollback:
 stage: rollback
 tags:
   - pd-test-windows-ml110q
 variables:
   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
   REGISTRY_PYPI_URL: $REGISTRY_PYPI_URL
   REGISTRY_SERVER: $REGISTRY_SERVER
   PACKAGE_VERSION: $TEST_ROLLBACK_VERSION
   VERIFICATION_URL: "http://ca2spdml110q:8000/api/health/"
 before_script:
   - . $VE_PATH
 script:
   - sh app/ci_scripts/rollback.sh package
 environment:
   name: test
 needs:
   - deploy-test
 rules:
   - if: $ENVIRONMENT == "test"
     when: on_failure

build-svt:
  tags:
    - pd-svt-windows-ml13q
  stage: build-svt
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $TEST_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
    REGISTRY_PYPI_USER: $TEST_REGISTRY_PYPI_USER
    REGISTRY_PYPI_PWD: $TEST_REGISTRY_PYPI_PWD
    PACKAGE_VERSION: $CURRENT_VERSION
  script:
    - python setup.py sdist
    - twine upload --repository-url $REGISTRY_PYPI_URL --username ${REGISTRY_PYPI_USER} --password ${REGISTRY_PYPI_PWD}  -r nexus dist/*
  artifacts:
    paths:
      - dist/
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - /^pd-release/*/
    variables: 
      - $ENVIRONMENT== "svt"

deploy-svt:
  tags:
    - pd-svt-windows-ml13q
  stage: deploy-svt
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $TEST_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
    PACKAGE_VERSION: $CURRENT_VERSION
    VERIFICATION_URL: "http://ca2spdml13q:8000/api/health/"
  before_script:
    - . $VE_PATH
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: svt
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - /^pd-release/*/
    variables: 
      - $ENVIRONMENT== "svt"

deploy-svt2:
  tags:
    - pd-svt-windows-ml16q
  stage: deploy-svt
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $TEST_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
    PACKAGE_VERSION: $CURRENT_VERSION
    VERIFICATION_URL: "http://ca2spdml16q:8000/api/health/"  
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: svt2
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - /^pd-release/*/
    variables: 
      - $ENVIRONMENT== "svt"

SVT-Rollback1:
 stage: rollback
 tags:
   - pd-svt-windows-ml13q
 variables:
   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
   REGISTRY_SERVER: $TEST_REGISTRY_SERVER
   REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
   PACKAGE_VERSION: $SVT_ROLLBACK_VERSION
   VERIFICATION_URL: "http://ca2spdml13q:8000/api/health/"
 before_script:
   - . $VE_PATH
 script:
   - sh app/ci_scripts/rollback.sh package
 environment:
   name: svt
 needs:
   - deploy-svt
 rules:
   - if: $ENVIRONMENT == "svt"
     when: on_failure

SVT-Rollback2:
 stage: rollback
 tags:
   - pd-svt-windows-ml16q
 variables:
   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
   REGISTRY_SERVER: $TEST_REGISTRY_SERVER
   REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
   PACKAGE_VERSION: $SVT_ROLLBACK_VERSION
   VERIFICATION_URL: "http://ca2spdml16q:8000/api/health/"
 before_script:
   - . $VE_PATH
 script:
   - sh app/ci_scripts/rollback.sh package
 environment:
   name: svt2
 needs:
   - deploy-svt2
 rules:
   - if: $ENVIRONMENT == "svt"
     when: on_failure

build-uat:
  tags:
    - ca2spdml03c
  stage: build-uat
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $TEST_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
    REGISTRY_PYPI_USER: $TEST_REGISTRY_PYPI_USER
    REGISTRY_PYPI_PWD: $TEST_REGISTRY_PYPI_PWD
    PACKAGE_VERSION: $CURRENT_VERSION
  script:
    - python setup.py sdist
    - twine upload --repository-url $REGISTRY_PYPI_URL --username ${REGISTRY_PYPI_USER} --password ${REGISTRY_PYPI_PWD}  -r nexus dist/*
  artifacts:
    paths:
      - dist/
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - /^pd-release/*/
    variables: 
      - $ENVIRONMENT== "uat"

deploy-uat:
  tags:
    - ca2spdml03c
  stage: deploy-uat
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $TEST_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
    PACKAGE_VERSION: $CURRENT_VERSION
    VERIFICATION_URL: "http://ca2spdml03c:8000/api/health"
  before_script:
    - . $VE_PATH
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: uat
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - /^pd-release/*/
    variables: 
      - $ENVIRONMENT== "uat"

deploy-uat2:
  tags:
    - ca2spdml06c
  stage: deploy-uat
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $TEST_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
    PACKAGE_VERSION: $CURRENT_VERSION
    VERIFICATION_URL: "http://ca2spdml06c:8000/api/health"
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: uat2
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - /^pd-release/*/
    variables: 
      - $ENVIRONMENT== "uat"

UAT-Rollback1:
 stage: rollback
 tags:
   - ca2spdml03c
 variables:
   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
   REGISTRY_SERVER: $TEST_REGISTRY_SERVER
   REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
   PACKAGE_VERSION: $UAT_ROLLBACK_VERSION
   VERIFICATION_URL: "http://ca2spdml03c:8000/api/health"
 before_script:
   - . $VE_PATH
 script:
   - sh app/ci_scripts/rollback.sh package
 environment:
   name: uat
 needs:
   - deploy-uat
 rules:
   - if: $ENVIRONMENT == "uat"
     when: on_failure

UAT-Rollback2:
 stage: rollback
 tags:
   - ca2spdml06c
 variables:
   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
   REGISTRY_SERVER: $TEST_REGISTRY_SERVER
   REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
   PACKAGE_VERSION: $UAT_ROLLBACK_VERSION
   VERIFICATION_URL: "http://ca2spdml06c:8000/api/health"
 before_script:
   - . $VE_PATH
 script:
   - sh app/ci_scripts/rollback.sh package
 environment:
   name: uat2
 needs:
   - deploy-uat2
 rules:
   - if: $ENVIRONMENT == "uat"
     when: on_failure

build-uat1:
  tags:
    - ca2spdml110d
  stage: build-uat1
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $TEST_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
    REGISTRY_PYPI_USER: $TEST_REGISTRY_PYPI_USER
    REGISTRY_PYPI_PWD: $TEST_REGISTRY_PYPI_PWD
    PACKAGE_VERSION: $CURRENT_VERSION
  script:
    - python setup.py sdist
    - twine upload --repository-url $REGISTRY_PYPI_URL --username ${REGISTRY_PYPI_USER} --password ${REGISTRY_PYPI_PWD}  -r nexus dist/*
  artifacts:
    paths:
      - dist/
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - feature/ci-cd-uat1
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "uat1"

deploy-uat1:
  tags:
    - ca2spdml110d
  stage: deploy-uat1
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $TEST_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
    PACKAGE_VERSION: $CURRENT_VERSION
    VERIFICATION_URL: "http://ca2spdml110d:8000/api/health"
  before_script:
    - . $VE_PATH
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: uat1
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - feature/ci-cd-uat1
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "uat1"

UAT1-Rollback:
 stage: rollback
 tags:
   - ca2spdml110d
 variables:
   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
   REGISTRY_SERVER: $TEST_REGISTRY_SERVER
   REGISTRY_PYPI_URL: $TEST_REGISTRY_PYPI_URL
   PACKAGE_VERSION: $UAT1_ROLLBACK_VERSION
   VERIFICATION_URL: "http://ca2spdml110d:8000/api/health"
 before_script:
   - . $VE_PATH
 script:
   - sh app/ci_scripts/rollback.sh package
 environment:
   name: uat1
 needs:
   - deploy-uat1
 rules:
   - if: $ENVIRONMENT == "uat1"
     when: on_failure

build-prod:
  tags:
    - ca2spdml03p
  stage: build-prod
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $PROD_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $PROD_REGISTRY_PYPI_URL
    REGISTRY_PYPI_USER: $PROD_REGISTRY_PYPI_USER
    REGISTRY_PYPI_PWD: $PROD_REGISTRY_PYPI_PWD
    PACKAGE_VERSION: $CURRENT_VERSION
  script:
    - python setup.py sdist
    - twine upload --repository-url $REGISTRY_PYPI_URL --username ${REGISTRY_PYPI_USER} --password ${REGISTRY_PYPI_PWD}  -r nexus dist/*
  artifacts:
    paths:
      - dist/
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "prod"

deploy-prod:
  tags:
    - ca2spdml03p
  stage: deploy-prod
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $PROD_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $PROD_REGISTRY_PYPI_URL
    PACKAGE_VERSION: $CURRENT_VERSION
    VERIFICATION_URL: "http://ca2spdml03p:8000/api/health"
  before_script:
    - . $VE_PATH
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: prod
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "prod"

deploy-prod2:
  tags:
    - ca2spdml06p
  stage: deploy-prod
  variables:
    GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
    REGISTRY_SERVER: $PROD_REGISTRY_SERVER
    REGISTRY_PYPI_URL: $PROD_REGISTRY_PYPI_URL
    PACKAGE_VERSION: $CURRENT_VERSION
    VERIFICATION_URL: "http://ca2spdml06p:8000/api/health"
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: prod2
  only:
    refs:
      - develop
      - develop-2.0.1
      - develop-2.1
      - /^pd-release/*/
    variables:
      - $ENVIRONMENT== "prod"

PROD-Rollback1:
 stage: rollback
 tags:
   - ca2spdml03p
 variables:
   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
   REGISTRY_SERVER: $PROD_REGISTRY_SERVER
   REGISTRY_PYPI_URL: $PROD_REGISTRY_PYPI_URL
   PACKAGE_VERSION: $PROD_ROLLBACK_VERSION
   VERIFICATION_URL: "http://ca2spdml03p:8000/api/health"
 before_script:
   - . $VE_PATH
 script:
   - sh app/ci_scripts/rollback.sh package
 environment:
   name: prod
 needs:
   - deploy-prod
 rules:
   - if: $ENVIRONMENT == "prod"
     when: on_failure

PROD-Rollback2:
 stage: rollback
 tags:
   - ca2spdml06p
 variables:
   GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
   REGISTRY_SERVER: $PROD_REGISTRY_SERVER
   REGISTRY_PYPI_URL: $PROD_REGISTRY_PYPI_URL
   PACKAGE_VERSION: $PROD_ROLLBACK_VERSION
   VERIFICATION_URL: "http://ca2spdml06p:8000/api/health"
 before_script:
   - . $VE_PATH
 script:
   - sh app/ci_scripts/rollback.sh package
 environment:
   name: prod2
 needs:
   - deploy-prod2
 rules:
   - if: $ENVIRONMENT == "prod"
     when: on_failure
      
      

      
      
