variables:
  BUILD_ENV: "pd-build-ui-backend-373"
  RUNNING_ENV: "pd-ci-ui-backend-373"
  PYTHON_PATH: "/D/Projects/PD/softwares/python/python-3.7.3"
  BASE_PYTHON_PATH: "D:/Projects/PD/softwares/python/python-3.7.3"
  VE_PATH: "${CI_BUILDS_DIR}/${RUNNING_ENV}/Scripts/activate.ps1"
  NSSM_PATH: "/D/Projects/PD/softwares/nssm/nssm-2.24/win64/nssm.exe"
  SERVICE_NAME: "pd-ci-ui-backend"
  PACKAGE: "pd-ui-backend"
  GIT_CLONE_PATH: "${CI_BUILDS_DIR}/${PACKAGE}"
  CI_DEBUG_TRACE: "false"


stages:
  - static_analysis
  - test
  - build
  - deploy

default:
  before_script:
    - sh app/ci_scripts/create_venv.sh
    - . $VE_PATH


flake8:
  tags:
    - pd-dev-windows-ml01q
  stage: static_analysis
  script:
    - flake8 --ignore=E ui-backend
  allow_failure: true # Remove it, when ready
  only:
    refs:
      - develop
      - merge_requests
    variables: 
      - $ENVIRONMENT== "dev"    
  
unit-tests:
  tags:
      - pd-dev-windows-ml01q
  stage: test
  before_script:
    - . $VE_PATH
  script:
    - python -m pytest -v --junit-xml=test_results.xml --cov=triage --cov-report=xml
  artifacts:
      paths:
      - test_results.xml
      - coverage.xml
  only:
    refs:
      - develop
      - merge_requests
    variables: 
      - $ENVIRONMENT== "dev"


build:
  tags:
    - pd-dev-windows-ml01q
  stage: build
  before_script:
    - . $VE_PATH 
  script:
    - python setup.py sdist
  artifacts:
    paths:
      - dist/
  only:
    refs:
      - develop
      - merge_requests
    variables: 
      - $ENVIRONMENT== "dev"
  
deploy-dev1:
  tags:
    - pd-dev-windows-ml01q
  stage: deploy
  variables:
    VERIFICATION_URL: "http://ca2spdml01q:8000/api/health/"  
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: dev
  only:
    refs:
      - develop
    variables: 
      - $ENVIRONMENT== "dev"

deploy-dev2:
  tags:
    - pd-dev-windows-ml06d
  stage: deploy
  variables:
    VERIFICATION_URL: "http://ca2spdml06d:8000/api/health/"  
  script:
    - sh app/ci_scripts/deploy.sh dist
  environment:
    name: dev2
  only:
    refs:
      - develop
    variables: 
      - $ENVIRONMENT== "dev"
