from .config_db import ConfigDb
from .documentpartslist_db import DocumentpartslistDb
from .fontinfo_db import FontinfoDb
from .iqvattribute_db import IqvattributeDb
from .iqvattributecandidate_db import IqvattributecandidateDb
from .iqvcharacter_db import IqvcharacterDb
from .iqvclassifiermodel_db import IqvclassifiermodelDb
from .iqvcountrymapping_db import IqvcountrymappingDb
from .iqvdocument_db import IqvdocumentDb
from .iqvdocumentcompare_db import IqvdocumentcompareDb
from .iqvdocumentdiff_db import IqvdocumentdiffDb
from .iqvdocumentfeedbackqc_db import IqvdocumentfeedbackqcDb
from .iqvdocumentfeedbackresults_db import IqvdocumentfeedbackresultsDb
from .iqvdocumentlink_db import IqvdocumentlinkDb
from .iqvdocumentmapping_db import IqvdocumentmappingDb
from .iqvdocumentprocess_db import IqvdocumentprocessDb
from .iqvexternallink_db import IqvexternallinkDb
from .iqvexternallinkelement_db import IqvexternallinkelementDb
from .iqvkeyvalueset_db import IqvkeyvaluesetDb
from .iqvlanguagemapping_db import IqvlanguagemappingDb
from .iqvline_db import IqvlineDb
from .iqvnumberinggroup_db import IqvnumberinggroupDb
from .iqvnumberinglevel_db import IqvnumberinglevelDb
from .iqvpageroi_db import IqvpageroiDb
from .iqvqcupdatetracking_db import IqvqcupdatetrackingDb
from .iqvredactioncategory_db import IqvredactioncategoryDb
from .iqvredactionprofile_db import IqvredactionprofileDb
from .iqvsubtext_db import IqvsubtextDb
from .iqvtablecolumn_db import IqvtablecolumnDb
from .iqvtablecolumnheader_db import IqvtablecolumnheaderDb
from .iqvtablerow_db import IqvtablerowDb
from .iqvword_db import IqvwordDb
from .languagecode_db import LanguagecodeDb
from .nlp_attribute_db import NlpAttributeDb
from .nlp_entity_db import NlpEntityDb
from .nlp_relation_db import NlpRelationDb
from .nlp_segment_db import NlpSegmentDb
from .nlp_system_mapping_db import NlpSystemMappingDb
from .iqvassessmentvisitrecord_db import IqvassessmentvisitrecordDb
from .iqvassessmentrecord_db import IqvassessmentrecordDb
from .iqvvisitrecord_db import IqvvisitrecordDb
from .q_event_log_entry_db import QEventLogEntryDb
from .documentparagraphs_db import DocumentparagraphsDb
from .documenttables_db import DocumenttablesDb
from .documentimages_db import DocumentimagesDb
from .documentitems_db import DocumentitemsDb
from .documentheaders_db import DocumentheadersDb
from .documentfooters_db import DocumentfootersDb
from .iqvdocumentvariable_db import IqvdocumentvariableDb
from sqlalchemy import create_engine
from .__base__ import SchemaBase

def create_schemas(URL):
    engine = create_engine(URL,echo = True)
    SchemaBase.metadata.create_all(engine)
