from sqlalchemy import Column,Index
from .__base__ import SchemaBase
from sqlalchemy.dialects.postgresql import DOUBLE_PRECISION,TEXT,VARCHAR,INTEGER,BOOLEAN,BIGINT,JSONB,BYTEA

class IqvlineDb(SchemaBase):
   __tablename__ = "iqvline_db"
   id = Column(VARCHAR(128),primary_key=True,nullable=False)
   SequenceID = Column(INTEGER,nullable=False)
   ParentID = Column(INTEGER,nullable=False)
   TopParentID = Column(INTEGER,nullable=False)
   doc_id = Column(TEXT)
   link_id = Column(TEXT)
   link_id_level2 = Column(TEXT)
   link_id_level3 = Column(TEXT)
   link_id_level4 = Column(TEXT)
   link_id_level5 = Column(TEXT)
   link_id_level6 = Column(TEXT)
   link_id_subsection1 = Column(TEXT)
   link_id_subsection2 = Column(TEXT)
   link_id_subsection3 = Column(TEXT)
   hierarchy = Column(VARCHAR(128),primary_key=True,nullable=False)
   iqv_standard_term = Column(TEXT)
   parent_id = Column(TEXT)
   group_type = Column(TEXT)
   Thickness = Column(INTEGER,nullable=False)
   ThicknessUnit = Column(INTEGER,nullable=False)
   X1 = Column(INTEGER,nullable=False)
   X2 = Column(INTEGER,nullable=False)
   X1Right = Column(INTEGER,nullable=False)
   X2Right = Column(INTEGER,nullable=False)
   Y1 = Column(INTEGER,nullable=False)
   Y2 = Column(INTEGER,nullable=False)
   Y1Lower = Column(INTEGER,nullable=False)
   Y2Lower = Column(INTEGER,nullable=False)
   bIncludedInBox = Column(BOOLEAN,nullable=False)
   bIsHorizontal = Column(BOOLEAN,nullable=False)
   BackgroundToForeground = Column(BOOLEAN,nullable=False)
   ForegroundToBackground = Column(BOOLEAN,nullable=False)

Index('iqvline_db_doc_id',IqvlineDb.doc_id)
Index('iqvline_db_doc_id_hierarchy',IqvlineDb.doc_id,IqvlineDb.hierarchy)
Index('iqvline_db_iqv_standard_term',IqvlineDb.iqv_standard_term)
Index('iqvline_db_link_id',IqvlineDb.link_id)
Index('iqvline_db_link_id_level2',IqvlineDb.link_id_level2)
Index('iqvline_db_link_id_level3',IqvlineDb.link_id_level3)
Index('iqvline_db_link_id_level4',IqvlineDb.link_id_level4)
Index('iqvline_db_link_id_level5',IqvlineDb.link_id_level5)
Index('iqvline_db_link_id_level6',IqvlineDb.link_id_level6)
Index('iqvline_db_link_id_subsection1',IqvlineDb.link_id_subsection1)
Index('iqvline_db_link_id_subsection2',IqvlineDb.link_id_subsection2)
Index('iqvline_db_link_id_subsection3',IqvlineDb.link_id_subsection3)
Index('iqvline_db_parent_id',IqvlineDb.parent_id,IqvlineDb.group_type)
Index('iqvline_db_parent_id_hierarchy',IqvlineDb.parent_id,IqvlineDb.hierarchy,IqvlineDb.group_type)
