from sqlalchemy import Column,Index
from .__base__ import SchemaBase
from sqlalchemy.dialects.postgresql import DOUBLE_PRECISION,TEXT,VARCHAR,INTEGER,BOOLEAN,BIGINT,JSONB,BYTEA

class IqvwordDb(SchemaBase):
   __tablename__ = "iqvword_db"
   id = Column(VARCHAR(128),primary_key=True,nullable=False)
   doc_id = Column(TEXT)
   link_id = Column(TEXT)
   link_id_level2 = Column(TEXT)
   link_id_level3 = Column(TEXT)
   link_id_level4 = Column(TEXT)
   link_id_level5 = Column(TEXT)
   link_id_level6 = Column(TEXT)
   link_id_subsection1 = Column(TEXT)
   link_id_subsection2 = Column(TEXT)
   link_id_subsection3 = Column(TEXT)
   hierarchy = Column(VARCHAR(128),primary_key=True,nullable=False)
   iqv_standard_term = Column(TEXT)
   parent_id = Column(TEXT)
   group_type = Column(TEXT)
   Blanks = Column(INTEGER,nullable=False)
   Bottom = Column(INTEGER,nullable=False)
   Class = Column(TEXT)
   Confidence = Column(DOUBLE_PRECISION,nullable=False)
   FontIndex = Column(DOUBLE_PRECISION,nullable=False)
   FontName = Column(TEXT)
   Formating = Column(INTEGER,nullable=False)
   Left = Column(INTEGER,nullable=False)
   LineIndex = Column(INTEGER,nullable=False)
   BlockIndex = Column(INTEGER,nullable=False)
   WordIndex = Column(INTEGER,nullable=False)
   PointSize = Column(INTEGER,nullable=False)
   Right = Column(INTEGER,nullable=False)
   Tag = Column(TEXT)
   Text = Column(TEXT)
   TextDerivedIsNumeric = Column(INTEGER,nullable=False)
   TextDerivedCase = Column(INTEGER,nullable=False)
   TextDerivedPrefix = Column(TEXT)
   TextDerivedSuffix = Column(TEXT)
   TextDerivedDeconstructed = Column(TEXT)
   TextLanguage = Column(TEXT)
   NLP_TextMatchReconstructed = Column(TEXT)
   NLP_TextMatch = Column(TEXT)
   NLP_ScoreMatch = Column(DOUBLE_PRECISION,nullable=False)
   GT_TextMatch = Column(TEXT)
   GT_ScoreMatch = Column(DOUBLE_PRECISION,nullable=False)
   Top = Column(INTEGER,nullable=False)
   textangle = Column(INTEGER,nullable=False)

Index('iqvword_db_doc_id',IqvwordDb.doc_id)
Index('iqvword_db_doc_id_hierarchy',IqvwordDb.doc_id,IqvwordDb.hierarchy)
Index('iqvword_db_iqv_standard_term',IqvwordDb.iqv_standard_term)
Index('iqvword_db_link_id',IqvwordDb.link_id)
Index('iqvword_db_link_id_level2',IqvwordDb.link_id_level2)
Index('iqvword_db_link_id_level3',IqvwordDb.link_id_level3)
Index('iqvword_db_link_id_level4',IqvwordDb.link_id_level4)
Index('iqvword_db_link_id_level5',IqvwordDb.link_id_level5)
Index('iqvword_db_link_id_level6',IqvwordDb.link_id_level6)
Index('iqvword_db_link_id_subsection1',IqvwordDb.link_id_subsection1)
Index('iqvword_db_link_id_subsection2',IqvwordDb.link_id_subsection2)
Index('iqvword_db_link_id_subsection3',IqvwordDb.link_id_subsection3)
Index('iqvword_db_parent_id',IqvwordDb.parent_id,IqvwordDb.group_type)
Index('iqvword_db_parent_id_hierarchy',IqvwordDb.parent_id,IqvwordDb.hierarchy,IqvwordDb.group_type)
