from sqlalchemy import Column, Float, Integer, String, Boolean
from app.db.base_class import Base


class DocumenttablesDb(Base):
    
    __tablename__ = "documenttables_db"


    
    bIsCheckbox = Column(Boolean, default=False)
    bIsChecked = Column(Boolean, default=False)
    bIsImage = Column(Boolean, default=False)
    bIsSharedString = Column(Boolean, default=False)
    bNoTranslate = Column(Boolean, default=False)
    bOutputImageCreated = Column(Boolean, default=False)
    bScannedOCR = Column(Boolean, default=False)
    BulletIndentationLevel = Column(Integer, default=-1)
    BulletTypeVal = Column(Integer, default=-1)
    CheckboxFill = Column(Float, default=0.0)
    contentTypeVal = Column(Integer, default=-1)
    doc_id = Column(String, nullable=True)
    DocumentRelId = Column(String, nullable=True)
    DocumentSequenceIndex = Column(Integer, default=-1)
    FooterSequence = Column(Integer, default=-1)
    group_type = Column(String, nullable=True)
    GT_ImageFilename = Column(String, nullable=True)
    GT_ScoreMatch = Column(Float, default=0.0)
    GT_TextMatch = Column(String, nullable=True)
    hAlignmentVal = Column(Integer, default=-1)
    HeaderSequence = Column(Integer, default=-1)
    hierarchy = Column(String, nullable=True)
    HorizontalResolution = Column(Float, default=0.0)
    htmlTagType = Column(String, nullable=True)
    Hue = Column(Integer, default=-1)
    id = Column(String, primary_key=True)
    ImageFormatVal = Column(String, nullable=True)
    ImageIndex = Column(Integer, default=-1)
    imagePaddingPixels = Column(Float, default=0.0)
    imageScaling = Column(Float, default=0.0)
    iqv_standard_term = Column(String, nullable=True)
    IsCopyOfRoiId = Column(String, nullable=True)
    IsTableCell = Column(Boolean, default=False)
    link_id = Column(String, nullable=True)
    link_id_level2 = Column(String, nullable=True)
    link_id_level3 = Column(String, nullable=True)
    link_id_level4 = Column(String, nullable=True)
    link_id_level5 = Column(String, nullable=True)
    link_id_level6 = Column(String, nullable=True)
    link_id_subsection1 = Column(String, nullable=True)
    link_id_subsection2 = Column(String, nullable=True)
    link_id_subsection3 = Column(String, nullable=True)
    m_PARENT_ROI_TYPEVal = Column(Integer, default=-1)
    m_ROI_TYPEVal = Column(Integer, default=-1)
    m_WORD_LAYOUTVal = Column(Integer, default=-1)
    OriginalROIHeightInches = Column(Float, default=0.0)
    OriginalROIWidthInches = Column(Float, default=0.0)
    OutputImageFilename = Column(String, nullable=True)
    OutputImageFilename_Cleaned = Column(String, nullable=True)
    OutputImageFilename_FinalImageProcessingOutput = Column(String, nullable=True)
    OutputImageFilename_FinalImageProcessingOutputToDropBox = Column(String, nullable=True)
    OutputImageFilename_OriginalSegment = Column(String, nullable=True)
    OutputImageFilename_RotationCorrection = Column(String, nullable=True)
    OutputImageFilename_RotationCorrectionToDropBox = Column(String, nullable=True)
    OutputImageFilename_Segments = Column(String, nullable=True)
    OutputImageFilename_SegmentsToDropBox = Column(String, nullable=True)
    OutputImageFilenameT = Column(String, nullable=True)
    OutputImageFilenameTDropBox = Column(String, nullable=True)
    PageID = Column(String, nullable=True)
    PageSequenceIndex = Column(Integer, default=-1)
    parent_id = Column(String, nullable=True)
    parentrectangle_height = Column(Integer, default=-1)
    parentrectangle_width = Column(Integer, default=-1)
    parentrectangle_x = Column(Integer, default=-1)
    parentrectangle_y = Column(Integer, default=-1)
    rectangle_height = Column(Integer, default=-1)
    rectangle_width = Column(Integer, default=-1)
    rectangle_x = Column(Integer, default=-1)
    rectangle_y = Column(Integer, default=-1)
    rectangleGlobalLocationOnPage_height = Column(Integer, default=-1)
    rectangleGlobalLocationOnPage_width = Column(Integer, default=-1)
    rectangleGlobalLocationOnPage_x = Column(Integer, default=-1)
    rectangleGlobalLocationOnPage_y = Column(Integer, default=-1)
    Rotation_MajorAxis = Column(Integer, default=-1)
    RotationCorrectionDegrees = Column(Float, default=0.0)
    scannedOCRCode = Column(String, nullable=True)
    Score = Column(Float, default=0.0)
    SegmentationMethodVal = Column(Integer, default=-1)
    SegmentationType = Column(Integer, default=-1)
    SequenceID = Column(Integer, default=-1)
    SlideIndex = Column(Integer, default=-1)
    SlideRelationshipId = Column(String, nullable=True)
    strText = Column(String, nullable=True)
    strTextTranslated = Column(String, nullable=True)
    tableCell_colIndex = Column(Integer, default=-1)
    tableCell_pageIndex = Column(Integer, default=-1)
    tableCell_rowIndex = Column(Integer, default=-1)
    tableCell_SharedStringIndex = Column(Integer, default=-1)
    tableCell_SheetCellReference = Column(String, nullable=True)
    tableCell_SheetColIndex = Column(Integer, default=-1)
    tableCell_SheetName = Column(String, nullable=True)
    tableCell_SheetRowIndex = Column(Integer, default=-1)
    textTypeVal = Column(Integer, default=-1)
    TranslatedTextNoSegmentation = Column(String, nullable=True)
    TranslationMatch = Column(Float, default=0.0)
    TranslationMethod1 = Column(String, nullable=True)
    UncorrectedImageFilename = Column(String, nullable=True)
    Value = Column(String, nullable=True)
    VerticalResolution = Column(Float, default=0.0)
  

