
TOC_CONSTANTS = {
                    "Protocol Summary":[
                        "Protocol Summary",
                        "Synopsis",
                        "Schema",
                        "Schedule of Activities (SoA)]"
                    ],
                    "Introduction":[
                        "Introduction",
                        "Study Rationale",
                        "Background",
                        "Benefit/Risk Assessment",
                        "Risk Assessment",
                        "Benefit Assessment",
                        "Overall Benefit: Risk Conclusion"
                    ],
                    "Objectives and [Endpoints and/or Estimands]":["Objectives and [Endpoints and/or Estimands]"],
                    "Study Design":[
                        "Study Design",
                        "Overall Design",
                        "Scientific Rationale for Study Design",
                        "Participant Input into Design",
                        "Justification for Dose",
                        "End of Study Definition"
                    ],
                    "Study Population":[
                        "Study Population",
                        "Inclusion Criteria",
                        "Exclusion Criteria",
                        "Lifestyle Considerations",
                        "Meals and Dietary Restrictions",
                        "Caffeine, Alcohol, and Tobacco",
                        "Activity",
                        "Screen Failures",
                        "Criteria for Temporarily Delaying [Enrollment/Randomization/Administration of Study Intervention Administration]"
                    ],
                    "Study Intervention(s) and Concomitant Therapy":[
                        "Study Intervention(s) and Concomitant Therapy",
                        "Study Intervention(s) Administered",
                        "Medical Devices",
                        "Preparation/Handling/Storage/Accountability",
                        "Measures to Minimize Bias: Randomization and Blinding",
                        "Study Intervention Compliance",
                        "Dose Modification",
                        "Retreatment Criteria",
                        "Continued Access to Study Intervention after the End of the Study",
                        "Treatment of Overdose",
                        "Concomitant Therapy",
                        "Rescue Medicine"
                    ],
                    "Discontinuation of Study Intervention and Participant Discontinuation/Withdrawal":[
                        "Discontinuation of Study Intervention and Participant Discontinuation/Withdrawal",
                        "Discontinuation of Study Intervention",
                        "Liver Chemistry Stopping Criteria",
                        "QTc Stopping Criteria",
                        "Temporary Discontinuation",
                        "Rechallenge",
                        "Participant Discontinuation/Withdrawal from the Study",
                        "Lost to Follow up"
                    ],
                    "Study Assessments and Procedures":[
                        "Study Assessments and Procedures",
                        "[Efficacy and/or Immunogenicity] Assessments",
                        "Safety Assessments",
                        "Physical Examinations",
                        "Vital Signs",
                        "Electrocardiograms",
                        "Clinical Safety Laboratory Assessments",
                        "Pregnancy Testing",
                        "Suicidal Ideation and Behavior Risk Monitoring",
                        "Adverse Events (AEs), Serious Adverse Events (SAEs), and Other Safety Reporting",
                        "Time Period and Frequency for Collecting AE and SAE Information",
                        "Method of Detecting AEs and SAEs",
                        "Follow-up of AEs and SAEs",
                        "Regulatory Reporting Requirements for SAEs",
                        "Pregnancy",
                        "Cardiovascular and Death Events",
                        "Disease-Related Events and/or Disease-Related Outcomes Not Qualifying as AEs or SAEs",
                        "Adverse Events of Special Interest",
                        "Medical Device Deficiencies",
                        "Pharmacokinetics",
                        "[Genetics and/or Pharmacogenomics]",
                        "Biomarkers",
                        "Immunogenicity Assessments",
                        "[Health Economics OR Medical Resource Utilization and Health Economics]"
                    ],
                    "Statistical Considerations":[
                        "Statistical Considerations",
                        "Statistical Hypotheses",
                        "Sample Size Determination",
                        "Analysis Sets",
                        "Statistical Analyses",
                        "General Considerations",
                        "Primary Endpoint(s)",
                        "Secondary Endpoint(s)",
                        "Tertiary/Exploratory Endpoint(s)",
                        "[Other/safety] Analysis",
                        "Other Analysis",
                        "Interim Analysis"
                    ],
                    "Supporting Documentation and Operational Considerations":[
                        "Supporting Documentation and Operational Considerations",
                        "Appendix 1: Regulatory, Ethical, and Study Oversight Considerations",
                        "Regulatory and Ethical Considerations",
                        "Financial Disclosure",
                        "Informed Consent Process",
                        "Data Protection",
                        "Committees Structure",
                        "Dissemination of Clinical Study Data",
                        "Data Quality Assurance",
                        "Source Documents",
                        "Study and Site Start and Closure",
                        "Publication Policy",
                        "Appendix 2: Clinical Laboratory Tests",
                        "Appendix 3: AEs and SAEs: Definitions and Procedures for Recording, Evaluating, Follow-up, and Reporting",
                        "Definition of AE",
                        "Definition of SAE",
                        "Recording and Follow-Up of AE and/or SAE",
                        "Reporting of SAEs",
                        "Appendix 4: Contraceptive and Barrier Guidance",
                        "Definitions",
                        "Contraception Guidance",
                        "Appendix 5: Genetics",
                        "Appendix 6: Liver Safety: Suggested Actions and Follow-up Assessments [and Study Intervention Rechallenge Guidelines]",
                        "Appendix 7: AEs, ADEs, SAEs, SADEs, USADEs and Device Deficiencies: Definitions and Procedures for Recording, Evaluating, Follow-up, and Reporting in Medical Device Studies",
                        "Definition of Medical Device AE and ADE",
                        "Definition of Medical Device SAE, SADE and USADE",
                        "Definition of Device Deficiency",
                        "Recording and Follow-Up of AE and/or SAE and Device Deficiencies",
                        "Reporting of SAEs",
                        "Reporting of SADEs",
                        "Appendix 8: Country-specific Requirements",
                        "Appendix 9: Abbreviations [and Definitions]",
                        "Appendix 10: Protocol Amendment History"
                    ],
                    "References":["References"],
                    "Unmapped":["Unmapped"]
}